apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: mlops-api-pod-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: mlops-api
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
